id: P000302
initial_creation_type: ocr
created_at: 10/03/2020
last_modified_at: 2021-12-16 15:32:53.873297
source_metadata:
  id: bdr:W24767
  title: ལམ་འབྲས་གཞུང་རྡོ་རྗེའི་ཚིག་རྐང་གི་རྣམ་འགྲེལ་བཅུ་གཅིག
  author: ''
  volumes:
    21a9879bb04a4bbaa5c278fb3d491bfa:
      image_group_id: I3852
      title: ''
      volume_number: 1
      total_pages: 542
      base_file: v001.txt
    221b0a860859456e976019e7bb469d3b:
      image_group_id: I3853
      title: ''
      volume_number: 2
      total_pages: 504
      base_file: v002.txt
    1f700f0a87784798ad9bd65a55a8ce53:
      image_group_id: I3854
      title: ''
      volume_number: 3
      total_pages: 502
      base_file: v003.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
